<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="nblap283" failures="2" tests="2" name="Test" time="37.902" errors="0" timestamp="01 Jun 2023 13:14:44 GMT">
  <testcase classname="resources.TestScript" name="test" time="20.823">
    <failure type="java.lang.AssertionError" message="expected [Thank you for your order!] but found [Thank you for your]">
      <![CDATA[java.lang.AssertionError: expected [Thank you for your order!] but found [Thank you for your]
	at AutomationPractice.SwagLabsAutomationPractice.CheckoutCompletepage.retriveSuccessmessage(CheckoutCompletepage.java:38)
	at resources.TestScript.test(TestScript.java:45)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase classname="AutomationPractice.SwagLabsAutomationPractice.CheckoutCompletepage" name="retriveSuccessmessage" time="0.0">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:70)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
	at com.sun.proxy.$Proxy12.getText(Unknown Source)
	at AutomationPractice.SwagLabsAutomationPractice.CheckoutCompletepage.retriveSuccessmessage(CheckoutCompletepage.java:33)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- retriveSuccessmessage -->
</testsuite> <!-- Test -->
